-- Recipeace — reference data seed (GENERATED — do not edit by hand).
-- Source of truth: src/data/cocktail-seed.ts   ·   Regenerate: npm run generate:seed
--
-- Idempotent: upserts keyed on natural keys (ingredient name, alias, and
-- substitution pair), so it is safe to re-run. Paste into the Supabase SQL
-- Editor and run AFTER the migrations.

begin;

-- 1. Ingredients (parent_id is resolved by name in step 2).
insert into public.ingredients (name, category, is_staple) values
  ('whiskey', 'spirit', false),
  ('bourbon', 'spirit', false),
  ('rye whiskey', 'spirit', false),
  ('scotch', 'spirit', false),
  ('islay scotch', 'spirit', false),
  ('irish whiskey', 'spirit', false),
  ('gin', 'spirit', false),
  ('london dry gin', 'spirit', false),
  ('old tom gin', 'spirit', false),
  ('plymouth gin', 'spirit', false),
  ('vodka', 'spirit', false),
  ('rum', 'spirit', false),
  ('white rum', 'spirit', false),
  ('gold rum', 'spirit', false),
  ('dark rum', 'spirit', false),
  ('aged rum', 'spirit', false),
  ('spiced rum', 'spirit', false),
  ('overproof rum', 'spirit', false),
  ('cachaça', 'spirit', false),
  ('tequila', 'spirit', false),
  ('blanco tequila', 'spirit', false),
  ('reposado tequila', 'spirit', false),
  ('añejo tequila', 'spirit', false),
  ('mezcal', 'spirit', false),
  ('brandy', 'spirit', false),
  ('cognac', 'spirit', false),
  ('armagnac', 'spirit', false),
  ('pisco', 'spirit', false),
  ('apple brandy', 'spirit', false),
  ('absinthe', 'spirit', false),
  ('pastis', 'spirit', false),
  ('orange liqueur', 'liqueur', false),
  ('triple sec', 'liqueur', false),
  ('cointreau', 'liqueur', false),
  ('grand marnier', 'liqueur', false),
  ('orange curaçao', 'liqueur', false),
  ('blue curaçao', 'liqueur', false),
  ('bitter liqueur', 'liqueur', false),
  ('campari', 'liqueur', false),
  ('aperol', 'liqueur', false),
  ('fernet branca', 'liqueur', false),
  ('averna', 'liqueur', false),
  ('cynar', 'liqueur', false),
  ('chartreuse', 'liqueur', false),
  ('green chartreuse', 'liqueur', false),
  ('yellow chartreuse', 'liqueur', false),
  ('bénédictine', 'liqueur', false),
  ('drambuie', 'liqueur', false),
  ('maraschino liqueur', 'liqueur', false),
  ('amaretto', 'liqueur', false),
  ('coffee liqueur', 'liqueur', false),
  ('cream liqueur', 'liqueur', false),
  ('crème de cassis', 'liqueur', false),
  ('crème de mûre', 'liqueur', false),
  ('crème de menthe', 'liqueur', false),
  ('crème de cacao', 'liqueur', false),
  ('crème de violette', 'liqueur', false),
  ('elderflower liqueur', 'liqueur', false),
  ('falernum', 'liqueur', false),
  ('allspice dram', 'liqueur', false),
  ('peach schnapps', 'liqueur', false),
  ('melon liqueur', 'liqueur', false),
  ('sloe gin', 'liqueur', false),
  ('limoncello', 'liqueur', false),
  ('vermouth', 'fortified_wine', false),
  ('sweet vermouth', 'fortified_wine', false),
  ('dry vermouth', 'fortified_wine', false),
  ('blanc vermouth', 'fortified_wine', false),
  ('sherry', 'fortified_wine', false),
  ('fino sherry', 'fortified_wine', false),
  ('manzanilla sherry', 'fortified_wine', false),
  ('amontillado sherry', 'fortified_wine', false),
  ('oloroso sherry', 'fortified_wine', false),
  ('pedro ximénez sherry', 'fortified_wine', false),
  ('lillet blanc', 'fortified_wine', false),
  ('cocchi americano', 'fortified_wine', false),
  ('port', 'fortified_wine', false),
  ('sparkling wine', 'wine', false),
  ('champagne', 'wine', false),
  ('prosecco', 'wine', false),
  ('cava', 'wine', false),
  ('red wine', 'wine', false),
  ('dry white wine', 'wine', false),
  ('bitters', 'bitters', false),
  ('angostura bitters', 'bitters', false),
  ('orange bitters', 'bitters', false),
  ('peychaud''s bitters', 'bitters', false),
  ('chocolate bitters', 'bitters', false),
  ('soda water', 'mixer', false),
  ('tonic water', 'mixer', false),
  ('cola', 'mixer', false),
  ('ginger beer', 'mixer', false),
  ('ginger ale', 'mixer', false),
  ('lemon-lime soda', 'mixer', false),
  ('grapefruit soda', 'mixer', false),
  ('lime juice', 'juice', false),
  ('lemon juice', 'juice', false),
  ('orange juice', 'juice', false),
  ('grapefruit juice', 'juice', false),
  ('pineapple juice', 'juice', false),
  ('cranberry juice', 'juice', false),
  ('tomato juice', 'juice', false),
  ('pomegranate juice', 'juice', false),
  ('simple syrup', 'syrup', false),
  ('rich simple syrup', 'syrup', false),
  ('demerara syrup', 'syrup', false),
  ('honey syrup', 'syrup', false),
  ('agave syrup', 'syrup', false),
  ('grenadine', 'syrup', false),
  ('orgeat', 'syrup', false),
  ('ginger syrup', 'syrup', false),
  ('passion fruit syrup', 'syrup', false),
  ('egg white', 'dairy', false),
  ('whole egg', 'dairy', false),
  ('heavy cream', 'dairy', false),
  ('half-and-half', 'dairy', false),
  ('milk', 'dairy', false),
  ('lime', 'produce', false),
  ('lemon', 'produce', false),
  ('orange', 'produce', false),
  ('grapefruit', 'produce', false),
  ('fresh mint', 'produce', false),
  ('fresh basil', 'produce', false),
  ('cucumber', 'produce', false),
  ('fresh ginger', 'produce', false),
  ('strawberry', 'produce', false),
  ('raspberry', 'produce', false),
  ('blackberry', 'produce', false),
  ('jalapeño', 'produce', false),
  ('pineapple', 'produce', false),
  ('lime wedge', 'garnish', false),
  ('lime wheel', 'garnish', false),
  ('lemon wedge', 'garnish', false),
  ('lemon wheel', 'garnish', false),
  ('lemon twist', 'garnish', false),
  ('orange twist', 'garnish', false),
  ('orange slice', 'garnish', false),
  ('maraschino cherry', 'garnish', false),
  ('luxardo cherry', 'garnish', false),
  ('cocktail olive', 'garnish', false),
  ('cocktail onion', 'garnish', false),
  ('mint sprig', 'garnish', false),
  ('grated nutmeg', 'garnish', false),
  ('cinnamon stick', 'garnish', false),
  ('salt rim', 'garnish', false),
  ('sugar rim', 'garnish', false),
  ('celery stalk', 'garnish', false),
  ('coffee beans', 'garnish', false),
  ('cream of coconut', 'other', false),
  ('coffee', 'other', false),
  ('espresso', 'other', false),
  ('worcestershire sauce', 'other', false),
  ('hot sauce', 'other', false),
  ('sugar cube', 'other', false),
  ('aquafaba', 'other', false),
  ('water', 'staple', true),
  ('ice', 'staple', true),
  ('crushed ice', 'staple', true),
  ('sugar', 'staple', true),
  ('salt', 'staple', true)
on conflict (name) do update set
  category = excluded.category,
  is_staple = excluded.is_staple;

-- 2. Resolve the is-a hierarchy: map each child name to its parent's id.
update public.ingredients c
set parent_id = p.id
from (values
  ('bourbon', 'whiskey'),
  ('rye whiskey', 'whiskey'),
  ('scotch', 'whiskey'),
  ('islay scotch', 'scotch'),
  ('irish whiskey', 'whiskey'),
  ('london dry gin', 'gin'),
  ('old tom gin', 'gin'),
  ('plymouth gin', 'gin'),
  ('white rum', 'rum'),
  ('gold rum', 'rum'),
  ('dark rum', 'rum'),
  ('aged rum', 'rum'),
  ('spiced rum', 'rum'),
  ('overproof rum', 'rum'),
  ('blanco tequila', 'tequila'),
  ('reposado tequila', 'tequila'),
  ('añejo tequila', 'tequila'),
  ('cognac', 'brandy'),
  ('armagnac', 'brandy'),
  ('pisco', 'brandy'),
  ('apple brandy', 'brandy'),
  ('triple sec', 'orange liqueur'),
  ('cointreau', 'orange liqueur'),
  ('grand marnier', 'orange liqueur'),
  ('orange curaçao', 'orange liqueur'),
  ('blue curaçao', 'orange liqueur'),
  ('campari', 'bitter liqueur'),
  ('aperol', 'bitter liqueur'),
  ('fernet branca', 'bitter liqueur'),
  ('averna', 'bitter liqueur'),
  ('cynar', 'bitter liqueur'),
  ('green chartreuse', 'chartreuse'),
  ('yellow chartreuse', 'chartreuse'),
  ('sweet vermouth', 'vermouth'),
  ('dry vermouth', 'vermouth'),
  ('blanc vermouth', 'vermouth'),
  ('fino sherry', 'sherry'),
  ('manzanilla sherry', 'sherry'),
  ('amontillado sherry', 'sherry'),
  ('oloroso sherry', 'sherry'),
  ('pedro ximénez sherry', 'sherry'),
  ('champagne', 'sparkling wine'),
  ('prosecco', 'sparkling wine'),
  ('cava', 'sparkling wine'),
  ('angostura bitters', 'bitters'),
  ('orange bitters', 'bitters'),
  ('peychaud''s bitters', 'bitters'),
  ('chocolate bitters', 'bitters'),
  ('crushed ice', 'ice')
) as m (child, parent)
join public.ingredients p on p.name = m.parent
where c.name = m.child;

-- 3. Aliases (brand / spelling variants -> canonical ingredient).
insert into public.ingredient_aliases (alias, ingredient_id)
select v.alias, i.id
from (values
  ('fresh lime juice', 'lime juice'),
  ('lime juice (fresh)', 'lime juice'),
  ('juice of 1 lime', 'lime juice'),
  ('fresh lemon juice', 'lemon juice'),
  ('juice of 1 lemon', 'lemon juice'),
  ('club soda', 'soda water'),
  ('seltzer', 'soda water'),
  ('sparkling water', 'soda water'),
  ('silver tequila', 'blanco tequila'),
  ('white tequila', 'blanco tequila'),
  ('anejo tequila', 'añejo tequila'),
  ('light rum', 'white rum'),
  ('silver rum', 'white rum'),
  ('cachaca', 'cachaça'),
  ('kahlua', 'coffee liqueur'),
  ('kahlúa', 'coffee liqueur'),
  ('tia maria', 'coffee liqueur'),
  ('baileys', 'cream liqueur'),
  ('irish cream', 'cream liqueur'),
  ('st-germain', 'elderflower liqueur'),
  ('st germain', 'elderflower liqueur'),
  ('luxardo', 'maraschino liqueur'),
  ('maraschino', 'maraschino liqueur'),
  ('midori', 'melon liqueur'),
  ('blackberry liqueur', 'crème de mûre'),
  ('creme de mure', 'crème de mûre'),
  ('blackcurrant liqueur', 'crème de cassis'),
  ('rosso vermouth', 'sweet vermouth'),
  ('red vermouth', 'sweet vermouth'),
  ('italian vermouth', 'sweet vermouth'),
  ('french vermouth', 'dry vermouth'),
  ('bianco vermouth', 'blanc vermouth'),
  ('lillet', 'lillet blanc'),
  ('pomegranate syrup', 'grenadine'),
  ('almond syrup', 'orgeat'),
  ('orgeat syrup', 'orgeat'),
  ('rich syrup', 'rich simple syrup'),
  ('simple syrup (1:1)', 'simple syrup'),
  ('angostura', 'angostura bitters'),
  ('aromatic bitters', 'angostura bitters'),
  ('peychauds', 'peychaud''s bitters'),
  ('calvados', 'apple brandy'),
  ('applejack', 'apple brandy'),
  ('scotch whisky', 'scotch'),
  ('coco lopez', 'cream of coconut'),
  ('coconut cream', 'cream of coconut'),
  ('tabasco', 'hot sauce'),
  ('worcestershire', 'worcestershire sauce'),
  ('brewed coffee', 'coffee'),
  ('egg whites', 'egg white'),
  ('champagne (brut)', 'champagne')
) as v (alias, ingredient)
join public.ingredients i on i.name = v.ingredient
on conflict (alias) do update set ingredient_id = excluded.ingredient_id;

-- 4. Substitutions ("in a pinch" swaps).
insert into public.ingredient_substitutions (ingredient_id, substitute_id, note)
select i.id, s.id, v.note
from (values
  ('bourbon', 'rye whiskey', 'rye is spicier and drier; bourbon rounder and sweeter'),
  ('cointreau', 'triple sec', 'generic triple sec is lower proof and less complex'),
  ('cointreau', 'grand marnier', 'grand marnier is cognac-based, richer and sweeter'),
  ('campari', 'aperol', 'aperol is lighter, sweeter, lower proof'),
  ('lillet blanc', 'cocchi americano', 'cocchi is more bitter and quinine-forward'),
  ('green chartreuse', 'yellow chartreuse', 'yellow is milder, sweeter, lower proof'),
  ('cognac', 'armagnac', 'armagnac is more rustic and robust'),
  ('lemon juice', 'lime juice', 'shifts the flavor profile; not identical'),
  ('simple syrup', 'demerara syrup', 'demerara adds molasses depth and color'),
  ('simple syrup', 'honey syrup', 'honey adds floral depth'),
  ('white rum', 'gold rum', 'gold adds light barrel character'),
  ('white rum', 'cachaça', 'cachaça is grassier and funkier'),
  ('ginger beer', 'ginger ale', 'ginger ale is milder and sweeter'),
  ('tequila', 'mezcal', 'mezcal adds smoke'),
  ('maraschino cherry', 'luxardo cherry', 'luxardo are premium; maraschino brighter and sweeter'),
  ('egg white', 'aquafaba', 'vegan substitute with the same foaming'),
  ('absinthe', 'pastis', 'pastis (Herbsaint/Pernod) is sweeter and lower proof'),
  ('orange curaçao', 'triple sec', 'close enough for most builds'),
  ('scotch', 'irish whiskey', 'irish is lighter and smoother; loses peat character')
) as v (ingredient, substitute, note)
join public.ingredients i on i.name = v.ingredient
join public.ingredients s on s.name = v.substitute
on conflict (ingredient_id, substitute_id) do update set note = excluded.note;

commit;