-- Stable URL identifiers for the per-ingredient pages (/ingredients/[slug]).
--
-- Slugs are derived from the ingredient name, so the taxonomy stays the single
-- source of truth: supabase/seed.sql emits them (generated by
-- scripts/generate-seed-sql.ts) and the backfill below covers rows that
-- already exist. public.slugify is the shared definition of the URL scheme —
-- keep it in step with the slugify() in scripts/generate-seed-sql.ts; the
-- ingredient-detail test asserts every seeded slug matches this function.

create function public.slugify(value text)
returns text
language sql
immutable
strict
set search_path = ''
as $$
  select trim(both '-' from regexp_replace(
    -- Fold the accented letters the taxonomy uses (crème, cachaça, jalapeño…)
    -- and drop apostrophes, so "peychaud's bitters" becomes
    -- peychauds-bitters rather than peychaud-s-bitters. Anything else
    -- non-alphanumeric collapses to a separator.
    translate(lower(value), 'àáâãäåçèéêëìíîïñòóôõöùúûüý''’', 'aaaaaaceeeeiiiinooooouuuuy'),
    '[^a-z0-9]+', '-', 'g'));
$$;

comment on function public.slugify(text) is
  'Canonical name → URL slug used for ingredient pages. Mirrored in '
  'scripts/generate-seed-sql.ts, which emits the slugs the seed inserts.';

alter table public.ingredients add column slug text;

-- Data migration for rows seeded before this column existed.
update public.ingredients set slug = public.slugify(name);

alter table public.ingredients
  alter column slug set not null,
  add constraint ingredients_slug_key unique (slug);